## <u> Introduction to NumPy </u>

- **NumPy** stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently. 
  - build on top of C programming language, which works at a lower level
  - has multidimensional array data structures that can represent vectors and matrices.
  - has a large number of optimized built-in mathematical functions
- When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.
- NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently - making it very suitable for solving machine learning problems.
- In fact, NumPy has become so popular that a lot of Python packages, such as Pandas, are built on top of NumPy
  

In [ ]:
!conda list numpy

In [ ]:
#how long does it take with Python ?
import time 
start = time.time()
numbers_python = []
for i in range(int(1e7)):
    numbers_python.append(i)
print (sum(numbers_python) / len(numbers_python))
print(time.time()-start)

In [ ]:
#how long does it take with NumPy ?
import time 
start = time.time()
import numpy as np
numbers_numpy = np.random.random((int(1e7))) 
print (np.mean(numbers_numpy))
print(time.time()-start)

## <u> Creating NumPy ndarrays </u>
 - `nd` stands for n-dimensional. An ndarray is a multidimensional array of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold either numbers or strings
 - There are several ways to create ndarrays in NumPy : 
     - Using regular Python lists 
     - Using built-in NumPy functions
     
### <u> Option 1: Using regular Python lists  </u>
 - **Reminder!:** `np.array()` is a function that returns an ndarray (it is NOT a class ) 

```python
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])
```

- **NDARRAY ATTRIBUTES** The shape of an array is the size along each of its dimensions. NumPy ndarrays have attributes that allow us to get information 
  - ` type() ` gives type of the array 
  - ` .dtype ` provides the type of the elements
  - ` .shape ` provides the shape of an ndarray
  - ` .size  ` provides the size of an ndarray 


- **Reminder!:** All the elements of an ndarray must be of the same type! we can't mix types in ndarray (different than Python lists).
   
```python
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])
#stored in memory as Unicode strings of 21 characters
```

- **RANK:** N-Dimensional arrays have rank N - (1D arrays are referred as rank 1,  2D arrays as a rank 2 arrays ... )

```python
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
# stored in memory as signed 64-bit integers
``` 

- **UPCASTING:** When mixed types are used to build an ndarray; since all the elements of an ndarray must be of the same type, NumPy upcasts the integers to floats in order to avoid losing precision in numerical computations.

```python 
# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])
print('The elements in z are of type:', z.dtype)
# stored in memory as signed 64-bit floats
```

- **Specify the particular dtype** This can be useful in cases when you don't want NumPy to accidentally choose the wrong data type, or when you only need certain amount of precision in your calculations and you want to save memory.

```python
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
```

- **SAVE TO FILE** Once you create an ndarray, you may want to save it to a file to be read later or to be used by another program by `save()` You can load the saved ndarray into a variable by using the `load()` function.


```python 
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)
```

In [6]:
# We create a 1D ndarray that contains only integers
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array(['a', 'b', 'c', 'd', 'e'])
# print x
print('x = ', x)
print('y = ', y)
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
#stored in memory as signed 64-bit integers

x =  [1 2 3 4 5]
y =  ['a' 'b' 'c' 'd' 'e']
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [7]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print x
print('x = ', x)
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
#stored in memory as Unicode strings of 5 characters

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


In [8]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
#stored in memory as Unicode strings of 21 characters


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


In [9]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print('Y = \n', Y)

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
# stored in memory as signed 64-bit integers

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [11]:
# UPCASTING
#We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
# stored in memory as signed 64-bit ints
print('The elements in y are of type:', y.dtype)
# stored in memory as signed 64-bit floats
print('The elements in z are of type:', z.dtype)
# stored in memory as signed 64-bit floats

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [ ]:
# specify particular dtype
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)

In [ ]:
# Save to File
We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

# We load the saved array from our current directory into variable y
# When loading an array from a file, make sure you include the name of the file together with the extension .npy, otherwise you will get an error. 
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

### <u> Option 2: Using built-in NumPy functions </u>

  - **np.zeros((num_rows,num_columns))** and **np.ones((num_rows,num_columns))**
    - **`X = np.zeros((3,4)),dtype=int` `X = np.ones((4,5))`**
    - creates an array with dtype float64 by default 
    - the data type can be changed by using the keyword `dtype`
    
    
  - **np.full(shape, constant value)**
    - **`X = np.full((2,3), 5)`**
    - creates an array with the same data type as the constant value by default  
    - the data type can be changed by using the keyword `dtype`
    
    
  - **Identity Matrix** by **np.eye(N)** 
     - **`X = np.eye(5)`**
     - is a square matrix that has only 1s in its main diagonal and zeros everywhere else
     - creates an array with the same data type as the constant value by default  
     - the data type can be changed by using the keyword `dtype`  
     
     
  - **A diagonal matrix** by **np.diag()** 
     - **`X = np.diag([10,20,30,50])`**
     - is a square matrix that only has values in its main diagonal.
     
     
  - **Range for evenly spaced values** by **np.arange(start,stop,step)**
     - to create a rank 1 ndarray `x = np.arange(10)` =>0 to 10, 10 exclusive 
     - for evenly spaced values within the half-open interval `x = np.arange(4,10)` =>4 to 10, 10 exclusive 
     - for step being the distance between two adjacent values. `x= np.arange(1,14,3)`
     - allows for non-integer steps but the output is inconsistent, due to the finite floating point precision
     
     
  - **Range for non-integer steps** by **np.linspace(start, stop, N)**
     - both the start and thestop values are included.
     - default number of elements in the specified interval will be N= 50.
     - uses the number of elements we want in a particular interval, instead of the step between values
     - **`x = np.linspace(0,25,10)`** vs **`x = np.linspace(0,25,10,endpoint=False)`**  
     
     
  - **Rank-2 ndarrays of any shape** by **np.reshape(ndarray, new_shape)** and **ndarray.reshape(new_shape)**
     - converts the given ndarray into the specified new_shape
     - should be compatible with the number of elements **`x = np.arange(20) x = np.reshape(x, (4,5))`**
     - **HINT! :** some functions can also be applied as methods. **`Y = np.arange(20).reshape(4, 5)`**
     - should be compatible with the number of elements in ndarray, no need to pass the ndarray as an argument
     - **``X = np.linspace(0,50,10, endpoint=False).reshape(5,2)``**
     
     
  - **Random Numbers** by **np.random.random(shape)** and **`np.random.randint(start, stop, size = shape)`**
  
     - to create random matrices, for example, when initializing the weights of a Neural Network
    
     - N x N ndarray with random floats in the half-open interval 0.0, 1.0 `X = np.random.random((3,3))`
     
     - N x N ndarray with random integers in the half-open interval `X = np.random.randint(4,15,size=(3,2))`
     
     - **np.random.normal(mean, standard deviation, size=shape)** :
        - create random ndarrays with numbers drawn from various probability distributions
        - creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian)  
          distribution with the given mean and standard deviation.`X = np.random.normal(0, 0.1, size=(1000,1000))` 
     

In [19]:
x = np.linspace(0,25,10)
print(x)
y = np.linspace(0,2511)
print(y)
z = np.linspace(0,25,10,endpoint=False)
print(z)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25. ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [20]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [23]:
X = np.random.random((3,3))
X
Y = np.random.randint(10,25,size=(4,5))
Y

array([[13, 15, 21, 19, 21],
       [22, 21, 22, 13, 24],
       [19, 19, 11, 21, 23],
       [16, 17, 21, 15, 20]])

In [34]:
N = np.random.normal(10, 0.1, size=(3,3))
N

array([[10.14045902, 10.12094925, 10.05414653],
       [ 9.94263963,  9.98389301,  9.95529527],
       [10.00604918,  9.82365626,  9.78899877]])

## <u> Accessing, Deleting, and Inserting Elements Into ndarrays </u>

- **Accessing**
  - Elements can be accessed using indices inside square brackets, `[]`

```python
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])
x[3] = 20

# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[0,0] = 20
```


- **Deleting** by **`np.delete(ndarray, elements, axis)`**
  - For rank 1 ndarrays the axis keyword is not required.
  - For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns

```python
# We delete the first and last element of x
x = np.delete(x, [0,4])

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)
```


- **Appending** by **`np.append(ndarray, elements, axis)`**

  - for rank 2 ndarrays the rows or columns must have the correct shape


- **Inserting** by **`np.insert(ndarray, index, elements, axis)`**
  - This function inserts the given list of elements to ndarray right before the given index along the specified axis


- **Stack ndarrays** by **`np.vstack()`** and **`np.hstack()`**
  - stack ndarrays on top of each other, or to stack them side by side
  - the shape of the ndarrays must match


In [ ]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])
print('This is Fifth (Last) Element in x:', x[4])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])
# We change the fourth element in x from 4 to 20
x[3] = 20

# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])
X[0,0] = 20

In [ ]:
#Appending

x = np.array([1, 2, 3, 4, 5])
Y = np.array([[1,2,3],[4,5,6]])
x = np.append(x, [7,8])

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)
# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1

In [ ]:
#Inserting

x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3],[7,8,9]])

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])
# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)
# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1

In [ ]:
#Stacking 
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))


## <u>  Slicing ndarrays </u>

- NumPy ndarrays can also be sliced, which means that ndarrays can be split in many different ways. Often in Machine Learning you will use slicing to separate data, as for example when dividing a data set into training, cross validation, and testing sets
- In general there're 3 types of slicing 

    **1. `ndarray[start:end]`** select elements between the start and end indices 
    
    **2. `ndarray[start:]`** select all elements from the start index till the last index
    
    **3. `ndarray[:end]`** select all elements from the first index till the end index
    
    -  the end index is excluded
    -  ndarrays can be multidimensional
    

- **Reminder!** It is important to note that when we perform slices on ndarrays and save them into new variables, as we did above, the data is not copied into the new variable

```python 
# if we make changes to Z, X changes as well
Z[2,2] = 555
#Because they've the same pointer to memory location
```

- **Copying ndarray** by **`np.copy(ndarray)`**
   - Creates new ndarrays that are completely independent of each other.
   - This function can also be used as a method, in the same way as with the reshape function.
   
```python
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# Now they've different pointers so an update on one doesn't affect another. 
```

- **Using an ndarray to make slices** 

```python

indices = np.array([1,3])
# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]
```

- **Using built-in functions** 

  - `np.diag(ndarray, k=N)` function extracts the elements along the diagonal defined by N. As default is k=0, which refers to the main diagonal. Values of k > 0 are used to select elements in diagonals above the main diagonal, and values of k < 0 are used to select elements in diagonals below the main diagonal.

  - `np.unique(ndarray)` function extracts only the unique elemtns in an ndarray.
  
```python

X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print('The unique elements in X are:',np.unique(X))

```

In [3]:
import numpy as np 
X = np.arange(20).reshape(4, 5)
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]
# We can select the same elements as above using method 2
W = X[1:,2:5]
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]
# We select all the elements in the 3rd row
v = X[2,:]
# We select all the elements in the 3rd column
q = X[:,2]
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

In [10]:
#np.diag(ndarray, k=N)
X = np.arange(25).reshape(5, 5)
# the elements in the main diagonal of X
print('z =', np.diag(X))

# the elements above the main diagonal of X
print('y =', np.diag(X, k=1))

# the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))


z = [ 0  6 12 18 24]
y = [ 1  7 13 19]
w =  [ 5 11 17 23]


## <u> Boolean Indexing, Set Operations, and Sorting </u> 

 - **Boolean Indexing** 
     - Used for situations where we don't know the indices of the elements we want to select
     - allowing us select elements using logical arguments instead of explicit indices

- **Set operations**
    - useful when comparing ndarrays, for example, to find common elements between two ndarrays
    - `np.intersect1d(x,y))`, `np.setdiff1d(x,y))`, `np.union1d(x,y))` are some of most frequently used examples. 
    
    
- **Sorting**
   - `np.sort() as function` sorts the ndrrays out of place and doesn't change the original ndarray being sorted.
   - `ndarray.sort() as method` sorts the ndarray in place and the original array will be changed to the sorted one.
   - `np.sort(np.unique(x))` sorts only the unique elements in x by combining the sort function with the unique
   -  **sorting rank 2 ndarrays** specify whether to sort by rows or columns by using the `axis keyword` 

In [ ]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)
# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1
# We print X
print('X = \n', X)

In [ ]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])
# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])
# We use set operations to compare x and y:
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

In [ ]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We sort x and print the sorted array using sort as a function.
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. 
print()
print('x after sorting:', x)

# We sort x but only keep the unique elements in x
print(np.sort(np.unique(x)))

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)

In [ ]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We sort the columns of X and print the sorted array
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print('X with sorted rows :\n', np.sort(X, axis = 1))

## <u> Arithmetic operations and Broadcasting </u> 

  - NumPy allows element-wise operations on ndarrays as well as matrix operations
  - In order to do element-wise operations, NumPy sometimes uses something called Broadcasting. 
  - Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays. 
  - When performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable. 

```Python 
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
# If you use the function approach, the functions usually have options that you can tweak using keywords
print('add(x,y) = ', np.add(x,y))
```

- We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

```python
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print('add(X,Y) = \n', np.add(X,Y))
```

- We can also apply mathematical functions : 
  - `print('EXP(x) =', np.exp(x))`
  - `print('SQRT(x) =',np.sqrt(x))`
  - `print('POW(x,2) =',np.power(x,2))`
  
- NumPy has a wide variety of statistical functions

```python
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])
print('Average of all elements in X:', X.mean())
print('Sum of all elements in X:', X.sum())
print('Standard Deviation of all elements in X:', X.std())
print('Median of all elements in X:', np.median(X))
print('Maximum value of all elements in X:', X.max())
print('Minimum value of all elements in X:', X.min())
```

- NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.
- It works behind the scenes to broadcast the number along the ndarray so that they have the same shape

```python 

# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

print('3 * X = \n', 3 * X)
print('3 + X = \n', 3 + X)
print('X - 3 = \n', X - 3)
print('X / 3 = \n', X / 3)
```

- Subject to certain constraints, Numpy can do the same for two ndarrays of different shapes
- NumPy is able to add 1 x N and N x 1 ndarrays to N x N ndarrays by broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes. In general, NumPy can do this provided that the smaller ndarray, such as the 1 x N ndarray can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is unambiguous.


In [11]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('x - y = ', x - y)
print('x * y = ', x * y)
print('x / y = ', x / y)
# If you use the function approach, the functions usually have options that you can tweak using keywords
print('add(x,y) = ', np.add(x,y))
print('subtract(x,y) = ', np.subtract(x,y))
print('multiply(x,y) = ', np.multiply(x,y))
print('divide(x,y) = ', np.divide(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
x - y =  [-4.5 -4.5 -4.5 -4.5]
x * y =  [ 5.5 13.  22.5 34. ]
x / y =  [0.18181818 0.30769231 0.4        0.47058824]
add(x,y) =  [ 6.5  8.5 10.5 12.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


In [12]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print('X - Y = \n', X - Y)
print('X * Y = \n', X * Y)
print('X / Y = \n', X / Y)

print('add(X,Y) = \n', np.add(X,Y))
print('subtract(X,Y) = \n', np.subtract(X,Y))
print('multiply(X,Y) = \n', np.multiply(X,Y))
print('divide(X,Y) = \n', np.divide(X,Y))

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]
X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]
X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]
X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]
add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]
subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]
multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]
divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [13]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))

print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))

print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))

print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))

print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))

print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]
Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]
Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]
Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]
Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]
Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [14]:
# Operate on two ndarrays of different shapes
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
